DELIMITER ;

INSERT INTO m_genre(`name`) values('action');
INSERT INTO m_genre(`name`) values('childish');
INSERT INTO m_genre(`name`) values('comedy');
INSERT INTO m_genre(`name`) values('terror');
INSERT INTO m_genre(`name`) values('Science fiction');
INSERT INTO m_genre(`name`) values('adventure');
INSERT INTO m_genre(`name`) values('suspense');

CALL register_movie('Un jefe en pañales',2017,'El bebé más inusual llega a la casa de Tim en un taxi, vestido de traje y cargando un maletín. La rivalidad instantánea entre hermanos debe ser puesta de lado cuando el jefe en pañales hace equipo con su hermano de siete años para detener el plan maligno del presidente de Puppy Co.',null,'Latino e Inglés subtitulada',null,'Full HD Bluray','Video H.264 2000kbps | Audio AAC 160kbps',6.4,null,'Tom McGrath',true,'2-childish,3-comedy,0-animation');
CALL register_movie('Megamente',2010,'Megamind es el supervillano más brillante que el mundo haya conocido. Y el que menos éxito tiene. Durante años ha estado intentando conquistar Metro City. Pero cada intento es un fracaso por culpa del superhéroe con capa llamado Metro Man, un héroe invencible hasta el día en que Megamind le mata de verdad en el curso de uno de sus malvados y enrevesados planes. De repente, Megamind ¡es un supervillano sin un superhéroe! De este modo, se da cuenta de que haber cumplido el sueño de su vida es lo peor que le ha podido pasar. Entonces, Megamind decide que la única forma de salir de su estancamiento es crear un nuevo héroe llamado Titán, que promete ser más grande, mejor y más fuerte de lo que Metro Man fue nunca. Rápidamente, Titán empieza a pensar que es mucho más divertido ser uno de los malos que uno de los buenos. Sólo que Titán no quiere conquistar el mundo, quiere destruirlo. Entonces, Megamind tiene que decidirse: ¿podrá derrotar a su diabólica creación? ¿Podrá el hombre más inteligente del mundo tomar una decisión inteligente de una vez por todas? ¿Podrá el malvado genio convertirse en el insólito héroe de su propia historia?',null,'Latino',null,'DVDRip','Buena',7.2,null,'Tom McGrath',true,'0-animation,1-action,3-comedy');
CALL register_movie('Madagascar 2: Escape al África',2008,'Abandonados en la lejana costa de Madagascar, nuestros neoyorquinos animales han concebido un plan tan alocado que posiblemente funcionará. Con precisión militar, los pingüinos han reparado, más o menos, un antiguo avión averiado. Una vez en el aire, esta inverosímil tripulación se mantiene volando el tiempo justo para llegar al lugar más salvaje de todos: las inmensas llanuras de África.',null,'Español latino',null,'DVDRip avi','Buena',6.6,null,'Tom McGrath',true,'0-animation,6-adventure,3-comedy,2-childish');